// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2M3Og8G77vZTmBgTPC7gXlb248eVl0s',
    appId: '1:61578749892:web:640621532b63bce0436691',
    messagingSenderId: '61578749892',
    projectId: 'food-delivery-fe1a0',
    authDomain: 'food-delivery-fe1a0.firebaseapp.com',
    storageBucket: 'food-delivery-fe1a0.firebasestorage.app',
    measurementId: 'G-9LRCPQTSZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiYyqcteoX-kbWQy6_s1bkL_c6Zja_3Q',
    appId: '1:61578749892:android:86c6eb90bf1b7069436691',
    messagingSenderId: '61578749892',
    projectId: 'food-delivery-fe1a0',
    storageBucket: 'food-delivery-fe1a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0WRGbSOl9A7tEj_eyxP04Y-S__amVM0s',
    appId: '1:61578749892:ios:6bca564457679b96436691',
    messagingSenderId: '61578749892',
    projectId: 'food-delivery-fe1a0',
    storageBucket: 'food-delivery-fe1a0.firebasestorage.app',
    iosBundleId: 'com.mk.fooddelivery.foodDelivery',
  );
}
